WIP Feature/colored multi select
dataware-tools/app-common pull request #443
Opened 2022-06-24 04:04 UTC by onose004

## What?
(概要など)
- MultiSelect の背景色を指定する関数 props を追加

## Why?
(モチベーションなど)
- MultiSelect の背景色を柔軟に変更するため

## See also [Optional]
- https://github.com/dataware-tools/dataware-tools/issues/5

## Screenshot or video [Optional]

2022-06-24 07:46 UTC, WatanabeToshimitsu commented
@onose004 

まずエラー自体について解説させてもらいます
```
npm ERR! While resolving: eslint-config-standard@16.0.3
npm ERR! Found: eslint-plugin-promise@6.0.0
npm ERR! node_modules/eslint-plugin-promise
npm ERR!   dev eslint-plugin-promise@"^6.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-promise@"^4.2.1 || ^5.0.0" from eslint-config-standard@[16](https://github.com/dataware-tools/app-common/runs/7036530450?check_suite_focus=true#step:5:17).0.3
npm ERR! node_modules/eslint-config-standard
npm ERR!   dev eslint-config-standard@"^16.0.3" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: eslint-plugin-promise@5.2.0
npm ERR! node_modules/eslint-plugin-promise
npm ERR!   peer eslint-plugin-promise@"^4.2.1 || ^5.0.0" from eslint-config-standard@16.0.3
npm ERR!   node_modules/eslint-config-standard
npm ERR!     dev eslint-config-standard@"^16.0.3" from the root project
```
app-common の devDependencies で eslint-plugin-promise の v6.0.0 を指定しているのに、devDependencies にある eslint-config-standard が peerDependencies に eslint-plugin-promise の v4.2.1 ~ v5 を指定しているから、npm がその矛盾に対してエラーを出しています

この辺を解決するための施策を main ブランチに最近施したので、[一度 master をマージしてみたらこのエラー自体は治りました](https://github.com/dataware-tools/app-common/runs/7036893949?check_suite_focus=true#step:5:1)


ただ、master をマージしただけだと [loki](https://loki.js.org/) というライブラリを使った[ビジュアルリグレッションテストの部分で  CI が落ちる](https://github.com/dataware-tools/app-common/runs/7036893949?check_suite_focus=true#step:6:375)ようになります
これに関しては意図通りの動作です
なので、master ブランチをマージした後に `npm install` をし直して、`npm run test:visual-regression` を実行してもらって、その出力を見ながら自己解決を図ってもらえると、CI で実行されるプロセスへの理解が進むかと思います
ただ、↓みたいな出力が出てこなかった場合は、そもそも loki 自体がうまく動いてない気がするので、早めに頼ってもらった方がいいかもしれません
![image](https://user-images.githubusercontent.com/72174933/175487524-de16d9e1-926d-4e9b-ae15-e07b1db655b3.png)

2022-06-24 08:15 UTC, onose004 commented
丁寧に説明してもらってありがとうございます！
stories 内の無視していたエラーを解決中なので、それと合わせてまた push します。

2022-06-24 11:41 UTC, WatanabeToshimitsu commented
@onose004 
うーーーーーーーーーーーーーん
一応軽く調べてみたものの、そのままこういう状況について述べた記述が見つからなかったので推測になります

型が unknown となるのは、単純に typescript が型を確定できないからだと踏んでいます
MultiSelect の型は[ジェネリクス](https://typescriptbook.jp/reference/generics)なので

- 型として使うならば、型引数に確定した型を与える(`typeof MultiSelect<sometypes>` みたいな記述)
- JSX として使うならば、型を確定できるような引数を与えて呼び出す(`<MultiSelect options={someArray}>` みたいな記述　普段はこの記述によっていい感じに型が推測されてることが多いです)

のどちらかの使い方でないと、型引数を使って定義された型は "未定義"、すなわち unknown として判定されるのかなと

なので、今回だと↓みたいな記述だと型がいい感じになるはずです

```
type MultiSelectStory = ComponentStoryObj<
  typeof MultiSelect<Option, boolean, boolean>
>;

export const Default: MultiSelectStory = {
略
};
```

---
以下、補足です　二つあります
どっちとも今回のコードでは全然重要じゃないことですが、１つ目は今後使う場面が出てくる気がするので是非読んでやってください

１つ目
Javascript で正しくオブジェクトであるかどうかを判定するためには `typeof varName === "object"` では不足です
[typeof のMDN](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/typeof#%E8%A7%A3%E8%AA%AC) か [suin さんの記事](https://zenn.dev/suin/books/8985cbff87b524e11c2b/viewer/01e63d) が詳しいんですが、`value !== null && typeof value === 'object'` としないと正確な検査になりません



２つ目
今回は typeof を使って MultiSelect という関数の型を引き出してるからコンパイルエラーにならないんですが、ジェネリクス自体に型引数を与えずに使うと普通にコンパイルエラーになります
具体的には、↓のコードは２行目で`Generic type 'MultiSelectT' requires 1 type argument(s).` というエラーが出ます
```
type GenericsType<TypeVar> = { test: TypeVar };
const variable: GenericsType = { test: "aaa" };
console.log(variable);
```
これについてはかなりエラーも解りやすいと思うので、今回の話は「typeof の仕様がちょっと悪いな」というのが僕の気持ちです

2022-06-28 01:52 UTC, onose004 commented
@WatanabeToshimitsu 
めちゃくちゃ丁寧に説明してもらってありがとうございます🙇
おかげさまで理解が深まりました！！
こちらで出ていたエラーは `yarn loki approve` を実行してなかったのが原因ぽかったです。
こちらに関しても理解深まりました🙇

2022-07-13 06:00 UTC, WatanabeToshimitsu commented on src/components/MultiSelect.tsx
> +  useEffect(() => {
この useEffect だけ消しといてもらえればマージしてもらってOKです！

2022-07-13 06:01 UTC, WatanabeToshimitsu requested changes
デバッグ用の console.log を見つけたのでそこだけ消してくれれば OK です！

2022-07-13 07:06 UTC, merged